export const initialFormData = {
  upload_token: null,
  datos_postulacion: {
    fecha_solicitud: "",
    puesto_aspirado: "",
    sueldo_deseado: 0,
  },
  candidato: {
    nombre_completo: "",
    correo_electronico: "",
    telefono_movil: "",
    documento_identidad: "",
    expedida_en: "",
    edad: 0,
    lugar_nacimiento: "",
    fecha_nacimiento: "",
  },
  detalles_personales: {
    observaciones: "",
    libreta_militar_numero: "",
    estado_civil: "",
    numero_hijos: 0,
    tipo_vivienda: "",
    valor_arriendo: 0,
    direccion_vivienda: "",
    tiempo_que_habita: "",
    barrio: "",
    localidad: "",
    telefono_fijo: "",
    con_quien_vive: "",
    eps: "",
    afp: "",
  },
  informacion_familiar: {
    conyuge: null,
    hijos: [],
    padres: [],
    hermanos: [],
  },
  informacion_academica: {
    formacion: "",
    titulo_obtenido: "",
    anio_terminacion: 0,
    otros_estudios: [],
    estudio_actual: [],
  },
  informacion_laboral: [],
  referencias_personales: [],
  datos_generales: {
    como_se_entero_empleo: "",
    tiene_familiares_empresa: false,
    lo_recomienda_alguien: false,
    ha_trabajado_con_nosotros: false,
    puede_viajar: false,
    dispuesto_cambiar_residencia: false,
    fecha_disponibilidad: "",
  },
  datos_economicos: {
    tiene_otros_ingresos: false,
    conyuge_trabaja: false,
    tiene_automovil_propio: false,
    tiene_deudas: false,
    gastos_mensuales: 0,
  },
  tallas: {
    talla_camisa_blusa: "",
    talla_pantalon: "",
    talla_calzado: "",
  },
};
