export const POSITIONS = [
  "Recepcionista",
  "Botones",
  "Camarero/a",
  "Chef",
  "Ayudante de cocina",
  "Housekeeping",
  "Gerente de hotel",
  "Contador/a",
  "Seguridad",
  "Mantenimiento",
  "Líder de Compra",
];
export const SEDES = [
  "Alto Prado",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Bucaramanga",
  "Pereira",
  "Manizales",
  "Cúcuta",
  "Ibagué",
];
